---
# - name: start and enable iptables service
#   ansible.builtin.service:
#     name: iptables
#     state: restarted
#     enabled: true
#   when: (ansible_hostname == "inetRouter")

- name: restart_network - OS RedHat
  ansible.builtin.service:
    name: network
    state: restarted
  when: ansible_os_family == "RedHat"

- name: start firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
    enabled: true
  when: (ansible_hostname == "inetRouter")
