Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 3
  end
  # Define two VMs with static private IP addresses.
  boxes = [
    { :name => "web",
      :ip => "192.168.11.170",
    },
    { :name => "log",
      :ip => "192.168.11.180",
    }
  ]
  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
    end
  end

  config.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
  config.vm.provision "shell", path: "./files/bootstrap.sh"
  config.vm.provision :ansible do |ansible|
    # ansible.verbose = 'vvvv'
    # ansible.playbook = 'provisioning/playbook.yml'
    # https://martincarstenbach.wordpress.com/2019/04/11/ansible-tipsntricks-provision-multiple-machines-in-parallel-with-vagrant-and-ansible/
    ansible.playbook = 'provisioning/check.yml'
    ansible.groups = {
      'webs' => ['web'],
      'logs' => ['log']
    }
    ansible.host_vars = {
      'web' => { 'host_ip' => '192.168.11.170' },
      'log' => { 'host_ip' => '192.168.11.180' }
    }
  end
end
