---
#sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
- name: set up repo
  replace:
    path: "{{ item }}"
    regexp: 'mirrorlist'
    replace: '#mirrorlist'
  with_items:
    - /etc/yum.repos.d/CentOS-Linux-AppStream.repo
    - /etc/yum.repos.d/CentOS-Linux-BaseOS.repo

#sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
- name: set up repo
  replace:
    path: "{{ item }}"
    regexp: '#baseurl=http://mirror.centos.org'
    replace: 'baseurl=http://vault.centos.org'
  with_items:
    - /etc/yum.repos.d/CentOS-Linux-AppStream.repo
    - /etc/yum.repos.d/CentOS-Linux-BaseOS.repo

# Установка пакета httpd (дополнительно сразу ставятся все пакеты, которые потребуются в данном задании
- name: install softs on CentOS
  yum:
    name: "{{  item  }}"
  loop:
    # - vim
    - wget
    - epel-release
    - httpd
    - tftp-server
    - dhcp-server
    - tftp-server
    - dhcp-server

- name: create folder for images
  file:
    path: "{{  item  }}"
    state: directory
    mode: 0755
  loop:
    - /images
    - /iso

- name: make xfs on sdb
  filesystem:
    dev: /dev/sdb
    fstype: xfs

- name: mount /dev/sdb to /images
  mount:
    path: /images
    src: /dev/sdb
    state: mounted
    fstype: xfs

# chown vagrant.vagrant /images/
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /images
    owner: vagrant
    group: vagrant
    mode: '0764'

# ----
- name: make xfs on sdb
  filesystem:
    dev: /dev/sdc
    fstype: xfs

- name: mount /dev/sdb to /images
  mount:
    path: /iso
    src: /dev/sdc
    state: mounted
    fstype: xfs

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /iso
    owner: vagrant
    group: vagrant
    mode: '0644'
