key_path: /etc/pki/tls/private/nginx-selfsigned.key
cert_path: /etc/pki/tls/certs/nginx-selfsigned.crt

# This is used for the nginx server configuration, but access to the
# WordPress site is not restricted by a named host.
nginx_port: 80
server_hostname: server.example.com
