# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
  	v.memory = 1024
  	v.cpus = 3
  end
  
  config.vm.define "pam" do |pam|
    pam.vm.provision "shell", path: "init_pam.sh"
  end
end

