# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
#  config.vm.box = "centos/8.4"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

#  config.vm.provision "shell", inline: <<-SHELL
#      yum install -y lvm lvm2
#  SHELL

end
