---
- name: create openvpn static.key
  shell: openvpn --genkey --secret /etc/openvpn/static.key
  when:
    - ansible_hostname == "server"


- name: copy to localhost static.key
  fetch:
    src: /etc/openvpn/static.key
    dest: '{{ cert_path }}'
    flat: yes
  when:
    - ansible_hostname == "server"

- name: copy static.key to client
  copy:
    src: static.key
    dest: /etc/openvpn/static.key
  when:
    - ansible_hostname == "client"

- name: copy openvpn conf to server
  template:
    src: tap-server.conf.j2
    dest: /etc/openvpn/server.conf
    owner: root
    mode: 0644

- name: start openvpn-server
  service:
    name: openvpn@server
    state: started
    enabled: yes
