# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
  	v.memory = 1024
  	v.cpus = 3
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "vv"
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end
end

