# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/7",
    :vm_name => "inetRouter",
    :net => [
      {adapter: 2, virtualbox__intnet: "router-net"},
      {adapter: 3, virtualbox__intnet: "router-net"},
      {ip: '192.168.50.11', adapter: 8},
    ]
  },
  :centralRouter => {
    :box_name => "centos/7",
    :vm_name => "centralRouter",
    :net => [
      {adapter: 2, virtualbox__intnet: "router-net"},
      {adapter: 3, virtualbox__intnet: "router-net"},
      {adapter: 4, virtualbox__intnet: "office1"},
      {ip: '192.168.50.12', adapter: 8},
    ]
  },
  :testServer1 => {
    :box_name => "centos/7",
    :vm_name => "testServer1",
    :net => [
      {adapter: 2, virtualbox__intnet: "office1"},
      {ip: '192.168.50.13', adapter: 8},
    ]
  },
  :testClient1 => {
    :box_name => "centos/7",
    :vm_name => "testClient1",
    :net => [
      {adapter: 2,  virtualbox__intnet: "office1"},
      {ip: '192.168.50.14', adapter: 8}
    ]
  },
  :testServer2 => {
    :box_name => "centos/7",
    :vm_name => "testServer2",
    :net => [
      {adapter: 2, virtualbox__intnet: "office1"},
      {ip: '192.168.50.15', adapter: 8},
    ]
  },
  :testClient2 => {
    :box_name => "centos/7",
    :vm_name => "testClient2",
    :net => [
      {adapter: 2,  virtualbox__intnet: "office1"},
      {ip: '192.168.50.16', adapter: 8}
    ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]


      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
      end
      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end
    end
  end

  config.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
  config.vm.provision "shell", path: "./files/bootstrap.sh"
  config.vm.provision :ansible do |ansible|
    # ansible.verbose = 'vvvv'
    # https://martincarstenbach.wordpress.com/2019/04/11/ansible-tipsntricks-provision-multiple-machines-in-parallel-with-vagrant-and-ansible/

    # Disable default limit to connect to all the machines
    ansible.limit = "all"
    ansible.playbook = 'provisioning/check.yml'
    ansible.groups = {
      'routers' => ['inetRouter', 'centralRouter']
    }
    ansible.host_vars = {
      'inetRouter' => { 'host_ip' => '192.168.50.11' },
      'centralRouter' => { 'host_ip' => '192.168.50.12' },
      'testServer1' => { 'host_ip' => '192.168.50.13' },
      'testClient1' => { 'host_ip' => '192.168.50.14' },
      'testServer2' => { 'host_ip' => '192.168.50.15' },
      'testClient2' => { 'host_ip' => '192.168.50.16' }
    }
  end
end
