---
roles:
  - src: geerlingguy.php
    version: 4.8.0

  - src: geerlingguy.nginx
    version: 3.1.1

  - src: geerlingguy.repo-epel
    version: 3.1.0

  - src: geerlingguy.node_exporter
    version: 1.0.2

  - src: geerlingguy.firewall
    version: 2.5.0

collections:
  - name: community.crypto
    version: 2.3.2

  - name: community.grafana
