---
- name: Drop  database with name 'bet'
  mysql_db:
    name: bet
    state: absent

- name: verify that the database bet does not exist
  shell: mysql -uroot -e "show databases;" | grep bet
  register: bet_found
  ignore_errors: true

- name: Create a new database with name 'bet'
  when: bet_found is failed
  mysql_db:
    name: bet
    state: present

- name: Import bet database
  when: bet_found is failed
  mysql_db:
    name: bet
    state: import
    target: /vagrant/provisioning/roles/mysql_master/files/bet.dmp

- name: create database user with database replication privileges
  mysql_user:
    name: repl
    host: '%'
    password: '!OtusLinux2022'
    priv: "*.*:REPLICATION SLAVE"
    state: present

- name: dump all databases to master.sql
  shell:
    mysqldump --all-databases --set-gtid-purged=OFF --triggers --routines --master-data --ignore-table=bet.events_on_demand --ignore-table=bet.v_same_event -uroot > /tmp/master.sql

