---
- name: Install epel
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install utility on RedHat OS
  yum:
    name:
      - tcpdump
      - traceroute
      - net-tools
      - nano
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: allow ssh-connect by password
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted


# TODO disable
- name: put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"

# - name: firewalld disable
#   service:
#     name: firewalld
#     state: stopped
#     enabled: no

# echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
- name: disable default route
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: DEFROUTE=no
  when: "'servers' in group_names"
