---
- name: start firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: add routes
  template:
    src: '{{  item  }}'
    dest: /etc/sysconfig/network-scripts/
  loop:
    - route-eth1
  notify:
    - restart_networking

- name: add forwarding to firewalld
  shell: |
    firewall-cmd --zone=external --change-interface=eth0 --permanent
    firewall-cmd --zone=external --change-interface=eth2 --permanent
    firewall-cmd --direct --permanent --add-rule ipv4 nat POSTROUTING 0 -o eth0 -j MASQUERADE
    firewall-cmd --direct --permanent --add-rule ipv4 filter FORWARD 0 -i eth1 -o eth0 -j ACCEPT
    firewall-cmd --direct --permanent --add-rule ipv4 filter FORWARD 0 -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT

- name: copy knock conf
  copy:
    src: knockd.conf
    dest: /etc/knockd.conf

- name: start knockd
  service:
    name: knockd
    state: started
    enabled: yes

- name: change knockd interface
  lineinfile:
    path: /etc/sysconfig/knockd
    regexp: '#OPTIONS=""'
    line: OPTIONS="-i eth1"
  notify:
    - restart_knockd

- name: open knockd ports
  firewalld:
    port: "{{  item  }}"
    permanent: yes
    state: enabled
  loop:
    - 8888/tcp
    - 7777/tcp
    - 6666/tcp

- name: deny ssh for default (public) zone
  firewalld:
    zone: public
    service: ssh
    state: disabled
    permanent: yes

- name: allow ssh-connect by password
  replace:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
  notify:
    - restart_sshd
