---
- name: Configure Monitor-server
  hosts: monitorServer
  remote_user: vagrant
  become: true
  roles:
    - common
    - monitor-server
  tags:
    - monitor

- name: Configure Backup-server
  hosts: backupsServer
  remote_user: vagrant
  become: true
  roles:
    - common
    - borgbackup-server
    - rsyslog-server
    - monitor-client
  tags:
    - backup

- name: Configure router
  hosts: inetRouter
  remote_user: vagrant
  become: true
  roles:
    - common
    - inetRouter
    - rsyslog-client
    - monitor-client
  tags:
    - routers

- name: Install web-server
  hosts: wordpressServer
  remote_user: vagrant
  become: true
  roles:
    - role: common
    - role: nginx-cert

    - role: geerlingguy.nginx
      tags: nginx

    - role: geerlingguy.php
      tags: php

    - role: wordpress
      tags: mysql

    - role: rsyslog-client
    - role: rsyslog-nginx
    - role: rsyslog-php-fpm

    - role: monitor-client
  tags:
    - web

- name: Install MySQL
  hosts: mysqlServer
  remote_user: vagrant
  become: true
  roles:
    - role: common

    - role: mysql

    - role: rsyslog-client

    - role: monitor-client

    - role: borgbackup-client
  tags:
    - mysql

