---
- name: Configure router
  hosts: inetRouter
  remote_user: vagrant
  become: true
  roles:
    - common
    - inetRouter
    # - rsyslog-client
    # - zabbix-agent
  tags:
    - routers

- name: Install web-server
  hosts: wordpressServer
  remote_user: vagrant
  become: true
  roles:
    - common
    - php-fpm
    - nginx
    - wordpress
    # - rsyslog-client
    # - zabbix-agent
  tags:
    - web
