---
- name: Configure router
  hosts: inetRouter
  remote_user: vagrant
  become: true
  roles:
    - common
    - inetRouter
    # - rsyslog-client
    # - zabbix-agent
  tags:
    - routers

- name: Install web-server
  hosts: wordpressServer
  remote_user: vagrant
  become: true
  roles:
    - role: common
    # - chusiang.php7
    - role: nginx-cert

    - role: geerlingguy.nginx
      tags: nginx

    - role: geerlingguy.php
      tags: php

    - role: wordpress
      tags: mysql
    # - rsyslog-client
    # - zabbix-agent
  tags:
    - web
