---
- name: Set FQDN hostname
  hostname:
    name: '{{ ipa_client_fqdn }}'

- name: Install ipa packages
  yum:
   name:
    - ipa-client
    - freeipa-admintools
    - bind-utils
   state: present


- name: Install ipa client
  command:
    cmd: |
      ipa-client-install -U
      --realm={{ ipa_realm }}
      --domain={{ ipa_domain }}
      --server={{ ipa_server_fqdn }}
      --ip-address={{ ipa_server_ip }}
      --hostname={{ ipa_client_fqdn }}
      --mkhomedir
      --force-ntpd
      -p {{ ipa_server_login }}
      -w {{ ipa_server_pass }}
    creates: /etc/ipa/default.conf
