- name: Create Filesystem for additional disks
  filesystem:
    fstype: xfs
    dev: '{{ item }}'
  loop:
    - '{{ data_disk }}'

- name: Mount Borg data disk
  mount:
    path: '{{ data_path }}'
    src: '{{ data_disk }}'
    fstype: xfs
    state: mounted

- name: Prepare all additional mount points
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ borg_user }}'
    group: '{{ borg_user }}'
    mode: '0700'
  loop:
    - '{{ data_path }}'
