---
- name: add user borg
  user:
    name: "{{  item  }}"
    state: present
    password: "{{ upassword | password_hash('sha512') }}"
    shell: /bin/bash
  loop:
    - borg

- name: create /home/borg/.ssh dir
  file:
    path:  /home/borg/.ssh
    state: directory
    owner: borg
    group: borg
    mode: 0700

- name: create authorized_keys
  file:
    path: /home/borg/.ssh/authorized_keys
    state: touch
    owner: borg
    group: borg
    mode: 0600

- name: Create Filesystem for additional disks
  import_tasks: create_disk.yml
