---

- name: add user borg
  user:
    name: "{{  item  }}"
    state: present
    password: "{{ upassword | password_hash('sha512') }}"
    shell: /bin/bash
  loop:
    - borg

- name: install python
  yum: 
    name: "{{ item }}"
    state: latest
  loop:
    - policycoreutils-python
    - python-pip

- name: Install pexpect throuhg pip
  become: true
  pip:
    name: "pexpect>=3.3"
    state: present

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: /root/.ssh/id_rsa

- name: copy public key to backup:/home/borg/.ssh/authorized_keys
  expect:
    command: scp -o "StrictHostKeyChecking=no" /root/.ssh/id_rsa.pub borg@192.168.11.160:/home/borg/.ssh/authorized_keys
    responses:
      Are you sure you want to continue connecting (yes/no)?: "yes"
      borg@192.168.11.160's password: "{{  borg_user_pass }}"

# debug
- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username_on_the_host
- debug: var=username_on_the_host



- name: init borg
  expect:
    command: borg init --encryption=repokey borg@192.168.11.160:/var/backup/
    responses:
      (?i)Enter new passphrase: "{{  borg_ps  }}"
      (?i)Enter same passphrase again: "{{  borg_ps  }}"
      (?i)Do you want your passphrase to be displayed for verification?: "n"
  tags: "borg_backup"

## borg_service
- name: configure borg-backup.service
  copy:
    src: borg-backup.service
    dest: /etc/systemd/system/
    owner: "root"
    group: "root"
    mode: '0644'
  tags: "borg_backup"

## borg_service
- name: configure borg-backup.timer
  copy:
    src: borg-backup.timer
    dest: /etc/systemd/system/
    owner: "root"
    group: "root"
    mode: '0644'
  notify:
    - borg-timer start service
  tags: "borg_backup"

- name: reload systremd
  systemd:
    daemon_reload: yes
  tags: "borg_backup"

- name: start & enable borg timer
  systemd:
    name: borg-backup.timer
    enabled: yes
    state: started  

- name: start & enable borg service
  systemd:
    name: borg-backup.service
    state: started 
  tags: "borg_backup"
