---
- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present
  notify: start nginx

- name: Copy nginx configuration for wordpress
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
     - restart nginx

- name: create self-signed certificate
  command: >
       openssl req -x509 -nodes -subj '/' -days 365
       -newkey rsa:2048 -sha256 -keyout {{ key_path }} -out {{ cert_path }}
  notify:
     - restart nginx

# - name: insert firewalld rule for nginx
#   firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
#   ignore_errors: true


# - name: WEB SERVER | CONFIG FIREWALLD FOR HTTP HTTPS
  # shell: firewall-cmd --permanent --zone=public --add-service=http ; firewall-cmd --permanent --zone=public --add-service=https ; firewall-cmd --reload


- name: http service state
  systemd:
    name: nginx
    state: started
    enabled: yes

# - include_tasks: setup-rsyslog-nginx.yml
